# -*- coding: utf-8 -*-
"""AtividadePython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1By14E2Kp56ji31NyrUpLQnEp2NUp8QI1

Extração
"""

import pandas as pd
import requests
import json


api_url = "https://sdw-2023-prd.up.railway.app"

#Extrair IDS do CSV
dados = pd.read_csv('DadosAPi.csv')
user_ids = dados['UserID'].tolist()
print(user_ids)

def get_user(id):
  response = requests.get(f'{api_url}/users/{id}')
  return response.json() if response.status_code == 200 else None

users = [user for id in user_ids if (user := get_user(id)) is not None]

print(json.dumps(users,indent = 2))

"""Transformação"""

def msg_generator(user):
    return f"{user['name']}, aqui está uma mensagem sobre a importância de manter suas economias: Investir pode ajudar a garantir seu futuro financeiro."
for user in users:
  msg = msg_generator(user)
  print(msg)
  user['news'].append(
      {
          "icon" : "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
          "description": msg
      }
  )

"""Carregamento (Load)"""

def atualizar (user):
  response = requests.put(f"{api_url}/users/{user['id']}",json = user)
  return True if response.status_code == 200 else False

for user in users:
  success = atualizar(user)
  print(f"User {user['name']} updated? {success}")